// ─── Mock Data for SuppX ──────────────────────────────────────────────────────
// All dummy data used when running without a backend

export const MOCK_CATEGORIES = [
  { _id: 'cat1', name: 'Proteins',               slug: 'proteins',                description: 'Whey, Casein & Plant-based protein powders' },
  { _id: 'cat2', name: 'Pre-Workout',             slug: 'pre-workout',             description: 'Energy, focus and pump formulas' },
  { _id: 'cat3', name: 'Creatine',                slug: 'creatine',                description: 'Creatine monohydrate and blends' },
  { _id: 'cat4', name: 'Vitamins and Supplements',slug: 'vitamins-and-supplements',description: 'Multivitamins, vitamin D & C' },
  { _id: 'cat5', name: 'Omega',                   slug: 'omega',                   description: 'Fish oil and omega-3 fatty acids' },
  { _id: 'cat6', name: 'Aminos',                  slug: 'aminos',                  description: 'BCAAs, EAAs and amino acid complexes' },
  { _id: 'cat7', name: 'Gainer',                  slug: 'gainer',                  description: 'Mass and weight gainer supplements' },
  { _id: 'cat8', name: 'Health and Wellness',     slug: 'health-and-wellness',     description: 'General health and wellness' },
];

export const MOCK_PRODUCTS = [
  {
    _id: 'p1',
    name: 'Whey Protein Gold Standard',
    slug: 'whey-protein-gold-standard',
    description: 'Premium whey protein isolate with 24g protein per serving. Crafted from ultra-pure whey, it delivers fast-absorbing amino acids right when your muscles need them most. Added digestive enzymes ensure maximum absorption with zero bloating.',
    price: 2999,
    originalPrice: 3999,
    brand: 'SuppX',
    stock: 150,
    category: { _id: 'cat1', name: 'Proteins', slug: 'proteins' },
    flavors: ['Chocolate Fudge', 'Vanilla Ice Cream', 'Strawberry Bliss', 'Cookies & Cream'],
    weights: ['500g', '1kg', '2kg'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    numReviews: 214,
    tags: ['whey', 'protein', 'isolate', 'muscle'],
    images: [
      'https://images.unsplash.com/photo-1593095948071-474c5cc2989d?w=600&q=80',
      'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=600&q=80',
    ],
    reviews: [
      { _id: 'r1', name: 'Rahul Sharma', rating: 5, comment: 'Best whey in India at this price point. Mixes perfectly, taste is amazing!', createdAt: '2025-03-10' },
      { _id: 'r2', name: 'Amit Verma', rating: 5, comment: 'Chocolate flavour is absolutely delicious. Good results in 3 weeks.', createdAt: '2025-02-20' },
      { _id: 'r3', name: 'Priya Singh', rating: 4, comment: 'Great product. Fast delivery too. Will order again.', createdAt: '2025-01-15' },
    ],
  },
  {
    _id: 'p2',
    name: 'Pre-Workout Ignite X',
    slug: 'pre-workout-ignite-x',
    description: 'Explosive pre-workout formula with 200mg caffeine, 6g L-Citrulline, 3.2g Beta-Alanine, and 1.5g Betaine Anhydrous. Experience skin-splitting pumps, laser focus, and energy that lasts your entire session — no crash guaranteed.',
    price: 1999,
    originalPrice: 2999,
    brand: 'SuppX',
    stock: 80,
    category: { _id: 'cat2', name: 'Pre-Workout', slug: 'pre-workout' },
    flavors: ['Blue Raspberry', 'Watermelon Wave', 'Green Apple Surge', 'Tropical Thunder'],
    weights: ['300g (30 servings)', '600g (60 servings)'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.9,
    numReviews: 189,
    tags: ['pre-workout', 'caffeine', 'pump', 'energy'],
    images: [
      'https://images.unsplash.com/photo-1546483875-ad9014c88eba?w=600&q=80',
      'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?w=600&q=80',
    ],
    reviews: [
      { _id: 'r4', name: 'Vikram Nair', rating: 5, comment: 'Insane pump! Best pre-workout I have ever tried. 100% recommend.', createdAt: '2025-04-01' },
      { _id: 'r5', name: 'Deepak Joshi', rating: 5, comment: 'Blue Raspberry flavour is on another level. Energy lasts 2+ hours.', createdAt: '2025-03-18' },
    ],
  },
  {
    _id: 'p3',
    name: 'Creatine Monohydrate Pure',
    slug: 'creatine-monohydrate-pure',
    description: 'Micronized creatine monohydrate — the most researched supplement in sports nutrition. 5g per serving for maximum strength, explosive power, and muscle volumization. No fillers, no flavors, just pure performance.',
    price: 999,
    originalPrice: 1499,
    brand: 'SuppX',
    stock: 320,
    category: { _id: 'cat3', name: 'Creatine', slug: 'creatine' },
    flavors: ['Unflavored'],
    weights: ['250g', '500g', '1kg'],
    isFeatured: false,
    isBestSeller: true,
    rating: 4.9,
    numReviews: 421,
    tags: ['creatine', 'strength', 'power', 'monohydrate'],
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80',
    ],
    reviews: [
      { _id: 'r6', name: 'Sandeep Kumar', rating: 5, comment: 'Genuine creatine. Strength went up noticeably within 2 weeks of loading.', createdAt: '2025-04-10' },
      { _id: 'r7', name: 'Rohan Gupta', rating: 5, comment: 'Pure quality. No clumping, mixes clean in water. My gym buddy switched too!', createdAt: '2025-03-22' },
      { _id: 'r8', name: 'Karan Mehta', rating: 4, comment: 'Solid creatine at a great price. Trust SuppX for authentic products.', createdAt: '2025-02-28' },
    ],
  },
  {
    _id: 'p4',
    name: 'BCAA 2:1:1 Intra-Workout',
    slug: 'bcaa-2-1-1-intra-workout',
    description: 'Clinically dosed 2:1:1 ratio of L-Leucine, L-Isoleucine, and L-Valine. Designed for muscle protein synthesis during and after training. Reduces muscle soreness, prevents catabolism, and accelerates recovery.',
    price: 1499,
    originalPrice: 1999,
    brand: 'SuppX',
    stock: 120,
    category: { _id: 'cat6', name: 'Aminos', slug: 'aminos' },
    flavors: ['Mango Tango', 'Pineapple Punch', 'Lemon Fizz', 'Watermelon'],
    weights: ['250g', '500g'],
    isFeatured: false,
    isBestSeller: true,
    rating: 4.6,
    numReviews: 97,
    tags: ['bcaa', 'amino', 'recovery', 'intra-workout'],
    images: [
      'https://images.unsplash.com/photo-1544367567-0f2fcb009e0b?w=600&q=80',
    ],
    reviews: [
      { _id: 'r9', name: 'Arjun Patel', rating: 5, comment: 'Mango flavour is really refreshing. Noticed less soreness after leg day.', createdAt: '2025-03-05' },
      { _id: 'r10', name: 'Neha Yadav', rating: 4, comment: 'Good BCAAs. Mixes well and tastes great sipped during workout.', createdAt: '2025-02-14' },
    ],
  },
  {
    _id: 'p5',
    name: 'Omega-3 Fish Oil 1000mg',
    slug: 'omega-3-fish-oil-1000mg',
    description: '1000mg premium fish oil per softgel with 300mg EPA and 200mg DHA from sustainably sourced deep-sea fish. Supports cardiovascular health, reduces inflammation, improves joint mobility, and enhances cognitive function.',
    price: 699,
    originalPrice: 999,
    brand: 'SuppX',
    stock: 450,
    category: { _id: 'cat5', name: 'Omega', slug: 'omega' },
    flavors: [],
    weights: ['60 softgels', '120 softgels', '180 softgels'],
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    numReviews: 312,
    tags: ['omega', 'fish-oil', 'heart', 'joints'],
    images: [
      'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=600&q=80',
    ],
    reviews: [
      { _id: 'r11', name: 'Suresh Iyer', rating: 5, comment: 'Joint pain reduced significantly after 30 days. Excellent quality.', createdAt: '2025-04-05' },
      { _id: 'r12', name: 'Meena Krishnan', rating: 5, comment: 'No fishy burps! Very clean omega. Will continue buying.', createdAt: '2025-03-20' },
    ],
  },
  {
    _id: 'p6',
    name: 'Multivitamin Daily Shield',
    slug: 'multivitamin-daily-shield',
    description: '23 essential vitamins and minerals packed into one daily tablet. Covers 100% RDA of Vitamin C, D3, B-complex, Zinc, and Magnesium. Designed for active individuals who demand complete micronutrient coverage.',
    price: 599,
    originalPrice: 899,
    brand: 'SuppX',
    stock: 600,
    category: { _id: 'cat4', name: 'Vitamins and Supplements', slug: 'vitamins-and-supplements' },
    flavors: [],
    weights: ['30 tablets', '60 tablets', '90 tablets'],
    isFeatured: true,
    isBestSeller: false,
    rating: 4.5,
    numReviews: 178,
    tags: ['vitamins', 'multivitamin', 'immunity', 'wellness'],
    images: [
      'https://images.unsplash.com/photo-1550572017-edd951aa8f72?w=600&q=80',
    ],
    reviews: [
      { _id: 'r13', name: 'Anita Desai', rating: 5, comment: 'Energy levels improved after 2 weeks. Recommend to everyone in my family.', createdAt: '2025-04-12' },
      { _id: 'r14', name: 'Ravi Pillai', rating: 4, comment: 'Good daily vitamin. No bad aftertaste and easy to swallow.', createdAt: '2025-03-08' },
    ],
  },
  {
    _id: 'p7',
    name: 'Mass Gainer Pro 3000',
    slug: 'mass-gainer-pro-3000',
    description: 'Engineered for serious hardgainers. 75g complex carbohydrates, 27g protein, 500+ calories per serving. Fortified with 3g creatine, 5g glutamine, and a full digestive enzyme blend. Fuel maximum muscle growth.',
    price: 3499,
    originalPrice: 4999,
    brand: 'SuppX',
    stock: 60,
    category: { _id: 'cat7', name: 'Gainer', slug: 'gainer' },
    flavors: ['Chocolate Fudge Brownie', 'Banana Caramel', 'Vanilla Cream'],
    weights: ['1kg', '3kg', '5kg'],
    isFeatured: true,
    isBestSeller: false,
    rating: 4.4,
    numReviews: 86,
    tags: ['gainer', 'mass', 'bulk', 'calories'],
    images: [
      'https://images.unsplash.com/photo-1540574163026-643ea20ade25?w=600&q=80',
    ],
    reviews: [
      { _id: 'r15', name: 'Harsh Malhotra', rating: 5, comment: 'Gained 4kg in 6 weeks with proper diet. Best gainer I have used.', createdAt: '2025-02-28' },
      { _id: 'r16', name: 'Tarun Shah', rating: 4, comment: 'Thick shake but worth it. Chocolate flavour is tasty.', createdAt: '2025-01-20' },
    ],
  },
  {
    _id: 'p8',
    name: 'Plant Protein Vegan Blend',
    slug: 'plant-protein-vegan-blend',
    description: 'Complete vegan protein sourced from organic pea protein, brown rice protein, and hemp seeds. 20g complete protein per serving with all 9 essential amino acids. Dairy-free, gluten-free, soy-free, and non-GMO.',
    price: 2499,
    originalPrice: 3200,
    brand: 'SuppX',
    stock: 90,
    category: { _id: 'cat1', name: 'Proteins', slug: 'proteins' },
    flavors: ['Dark Chocolate', 'Vanilla Bean', 'Unflavored'],
    weights: ['500g', '1kg'],
    isFeatured: true,
    isBestSeller: false,
    rating: 4.6,
    numReviews: 63,
    tags: ['vegan', 'plant-protein', 'dairy-free', 'pea-protein'],
    images: [
      'https://images.unsplash.com/photo-1490645935967-10de6ba17061?w=600&q=80',
    ],
    reviews: [
      { _id: 'r17', name: 'Pooja Menon', rating: 5, comment: 'Finally a vegan protein that actually tastes good! No chalky texture.', createdAt: '2025-03-30' },
      { _id: 'r18', name: 'Aditya Rao', rating: 4, comment: 'Clean ingredients, good mixability. Happy to switch from whey.', createdAt: '2025-03-12' },
    ],
  },
  {
    _id: 'p9',
    name: 'EAA Complete Recovery Formula',
    slug: 'eaa-complete-recovery',
    description: 'All 9 essential amino acids in clinically effective doses. Contains 3g leucine for maximal mTOR activation, plus electrolytes for hydration. Ideal for sipping during training or between meals to preserve muscle mass.',
    price: 1799,
    originalPrice: 2299,
    brand: 'SuppX',
    stock: 110,
    category: { _id: 'cat6', name: 'Aminos', slug: 'aminos' },
    flavors: ['Grape Burst', 'Orange Mango', 'Mixed Berry'],
    weights: ['300g (30 servings)', '600g (60 servings)'],
    isFeatured: false,
    isBestSeller: false,
    rating: 4.7,
    numReviews: 54,
    tags: ['eaa', 'amino', 'recovery', 'essential'],
    images: [
      'https://images.unsplash.com/photo-1476480862126-209bfaa8edc8?w=600&q=80',
    ],
    reviews: [
      { _id: 'r19', name: 'Siddharth Bose', rating: 5, comment: 'Grape flavour is amazing. Recovery is noticeably faster.', createdAt: '2025-04-08' },
    ],
  },
  {
    _id: 'p10',
    name: 'Vitamin D3 + K2 (5000 IU)',
    slug: 'vitamin-d3-k2-5000iu',
    description: 'Synergistic D3 + K2 combo for optimal calcium metabolism and bone health. Vitamin K2 (MK-7 form) ensures calcium goes to bones, not arteries. Essential for anyone living indoors or in low-sunlight regions.',
    price: 499,
    originalPrice: 699,
    brand: 'SuppX',
    stock: 800,
    category: { _id: 'cat4', name: 'Vitamins and Supplements', slug: 'vitamins-and-supplements' },
    flavors: [],
    weights: ['60 capsules', '120 capsules'],
    isFeatured: false,
    isBestSeller: true,
    rating: 4.9,
    numReviews: 387,
    tags: ['vitamin-d', 'vitamin-k2', 'bone-health', 'immunity'],
    images: [
      'https://images.unsplash.com/photo-1619566636858-adf3ef46400b?w=600&q=80',
    ],
    reviews: [
      { _id: 'r20', name: 'Geeta Bhandari', rating: 5, comment: 'Vitamin D levels were very low. After 3 months of this, back to normal!', createdAt: '2025-04-14' },
      { _id: 'r21', name: 'Yogesh Tiwari', rating: 5, comment: 'Good quality capsules. Definitely recommend the D3+K2 combo.', createdAt: '2025-03-25' },
    ],
  },
  {
    _id: 'p11',
    name: 'Caffeine + L-Theanine Stack',
    slug: 'caffeine-l-theanine-stack',
    description: 'The nootropic duo used by peak performers. 200mg natural caffeine paired with 200mg L-theanine delivers clean, jitter-free energy, improved reaction time, and enhanced focus — without the anxiety spike of coffee alone.',
    price: 799,
    originalPrice: 1199,
    brand: 'SuppX',
    stock: 200,
    category: { _id: 'cat2', name: 'Pre-Workout', slug: 'pre-workout' },
    flavors: [],
    weights: ['60 capsules', '90 capsules'],
    isFeatured: false,
    isBestSeller: false,
    rating: 4.8,
    numReviews: 143,
    tags: ['caffeine', 'focus', 'nootropic', 'energy', 'l-theanine'],
    images: [
      'https://images.unsplash.com/photo-1512054502232-10a0a035d672?w=600&q=80',
    ],
    reviews: [
      { _id: 'r22', name: 'Divya Kapoor', rating: 5, comment: 'No jitters, just smooth energy. Perfect for work and workouts!', createdAt: '2025-04-02' },
      { _id: 'r23', name: 'Manish Aggarwal', rating: 5, comment: 'Better than coffee. Focus lasts 4-5 hours without any crash.', createdAt: '2025-03-15' },
    ],
  },
  {
    _id: 'p12',
    name: 'Creatine HCL Advanced Formula',
    slug: 'creatine-hcl-advanced',
    description: 'Creatine Hydrochloride is 40x more soluble than monohydrate — no loading phase, no water retention, no bloating. 1.5g per serving provides equivalent strength benefits to 5g of creatine monohydrate.',
    price: 1499,
    originalPrice: 1999,
    brand: 'SuppX',
    stock: 130,
    category: { _id: 'cat3', name: 'Creatine', slug: 'creatine' },
    flavors: ['Unflavored', 'Fruit Punch'],
    weights: ['90g (60 servings)', '180g (120 servings)'],
    isFeatured: false,
    isBestSeller: false,
    rating: 4.6,
    numReviews: 71,
    tags: ['creatine', 'hcl', 'strength', 'no-loading', 'no-bloat'],
    images: [
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80',
    ],
    reviews: [
      { _id: 'r24', name: 'Abhishek Tomar', rating: 5, comment: 'No bloating at all! Huge advantage over regular creatine.', createdAt: '2025-03-28' },
      { _id: 'r25', name: 'Kavita Nair', rating: 4, comment: 'Switched from monohydrate. Much easier on the stomach.', createdAt: '2025-02-18' },
    ],
  },
  {
    _id: 'p13',
    name: 'Casein Protein Night Recovery',
    slug: 'casein-protein-night-recovery',
    description: 'Slow-digesting micellar casein provides a sustained 7-8 hour release of amino acids — perfect before bed. Protects muscle from overnight catabolism and wakes you up in full recovery mode.',
    price: 2799,
    originalPrice: 3500,
    brand: 'SuppX',
    stock: 70,
    category: { _id: 'cat1', name: 'Proteins', slug: 'proteins' },
    flavors: ['Chocolate Midnight', 'Vanilla Dream', 'Unflavored'],
    weights: ['500g', '1kg'],
    isFeatured: true,
    isBestSeller: false,
    rating: 4.7,
    numReviews: 58,
    tags: ['casein', 'protein', 'night', 'recovery', 'slow-release'],
    images: [
      'https://images.unsplash.com/photo-1543339308-43e59d6b73a6?w=600&q=80',
    ],
    reviews: [
      { _id: 'r26', name: 'Nitin Rawat', rating: 5, comment: 'Waking up less sore since using this before bed. Game changer!', createdAt: '2025-04-06' },
    ],
  },
  {
    _id: 'p14',
    name: 'Ashwagandha KSM-66 Extract',
    slug: 'ashwagandha-ksm66-extract',
    description: 'Premium KSM-66 ashwagandha root extract — the most bioavailable form. Clinically shown to reduce cortisol by 28%, boost testosterone, improve VO2 max, and enhance sleep quality. 600mg per serving.',
    price: 849,
    originalPrice: 1199,
    brand: 'SuppX',
    stock: 250,
    category: { _id: 'cat8', name: 'Health and Wellness', slug: 'health-and-wellness' },
    flavors: [],
    weights: ['60 capsules', '90 capsules'],
    isFeatured: true,
    isBestSeller: true,
    rating: 4.8,
    numReviews: 226,
    tags: ['ashwagandha', 'adaptogen', 'stress', 'testosterone', 'sleep'],
    images: [
      'https://images.unsplash.com/photo-1611241893603-3c359704e0ee?w=600&q=80',
    ],
    reviews: [
      { _id: 'r27', name: 'Pradeep Sinha', rating: 5, comment: 'Sleep quality improved dramatically. Stress is much lower. 10/10!', createdAt: '2025-04-11' },
      { _id: 'r28', name: 'Sneha Reddy', rating: 5, comment: 'KSM-66 is the real deal. Energy and mood have both improved.', createdAt: '2025-03-24' },
    ],
  },
  {
    _id: 'p15',
    name: 'Zinc + Magnesium ZMA Formula',
    slug: 'zinc-magnesium-zma-formula',
    description: 'The classic ZMA stack: 30mg Zinc Monomethionine, 450mg Magnesium Aspartate, and 10.5mg Vitamin B6. Supports anabolic hormone production, deeper sleep, and faster overnight recovery. Take 30 min before bed.',
    price: 649,
    originalPrice: 899,
    brand: 'SuppX',
    stock: 340,
    category: { _id: 'cat4', name: 'Vitamins and Supplements', slug: 'vitamins-and-supplements' },
    flavors: [],
    weights: ['60 capsules', '90 capsules'],
    isFeatured: false,
    isBestSeller: true,
    rating: 4.7,
    numReviews: 189,
    tags: ['zma', 'zinc', 'magnesium', 'sleep', 'testosterone'],
    images: [
      'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&q=80',
    ],
    reviews: [
      { _id: 'r29', name: 'Rakesh Pandey', rating: 5, comment: 'Sleep is much deeper and I wake up fresh. Great value for money!', createdAt: '2025-03-18' },
      { _id: 'r30', name: 'Shreya Kulkarni', rating: 4, comment: 'Good ZMA. Take it 30 min before bed as instructed and it works.', createdAt: '2025-02-25' },
    ],
  },
  {
    _id: 'p16',
    name: 'Glutamine Recovery Support',
    slug: 'glutamine-recovery-support',
    description: '5g micronized L-Glutamine per serving — the most abundant amino acid in muscle tissue. Speeds up gut health, reduces muscle breakdown post-workout, and supports immune system function during intense training.',
    price: 899,
    originalPrice: 1299,
    brand: 'SuppX',
    stock: 180,
    category: { _id: 'cat6', name: 'Aminos', slug: 'aminos' },
    flavors: ['Unflavored'],
    weights: ['250g', '500g'],
    isFeatured: false,
    isBestSeller: false,
    rating: 4.5,
    numReviews: 92,
    tags: ['glutamine', 'recovery', 'gut-health', 'immune'],
    images: [
      'https://images.unsplash.com/photo-1517836357463-d25dfeac3438?w=600&q=80',
    ],
    reviews: [
      { _id: 'r31', name: 'Anjali Sharma', rating: 5, comment: 'Gut health improved and recovery is faster. Mixing it with whey now.', createdAt: '2025-04-03' },
    ],
  },
];

export const MOCK_ORDERS = [
  {
    _id: 'ord1',
    user: { _id: 'user1', name: 'Rahul Sharma', email: 'rahul@example.com' },
    items: [
      { product: 'p1', name: 'Whey Protein Gold Standard', image: MOCK_PRODUCTS[0].images[0], price: 2999, quantity: 1, flavor: 'Chocolate Fudge', weight: '1kg' },
      { product: 'p2', name: 'Pre-Workout Ignite X', image: MOCK_PRODUCTS[1].images[0], price: 1999, quantity: 1, flavor: 'Blue Raspberry', weight: '300g (30 servings)' },
    ],
    shippingAddress: { name: 'Rahul Sharma', phone: '9876543210', street: '45 MG Road', city: 'Gurugram', state: 'Haryana', pincode: '122001' },
    paymentMethod: 'UPI',
    paymentStatus: 'paid',
    orderStatus: 'delivered',
    itemsPrice: 4998,
    shippingPrice: 0,
    totalPrice: 4998,
    trackingNumber: 'DELHV2025001234',
    createdAt: '2025-04-01T10:30:00Z',
  },
  {
    _id: 'ord2',
    user: { _id: 'user1', name: 'Rahul Sharma', email: 'rahul@example.com' },
    items: [
      { product: 'p3', name: 'Creatine Monohydrate Pure', image: MOCK_PRODUCTS[2].images[0], price: 999, quantity: 2, flavor: 'Unflavored', weight: '500g' },
    ],
    shippingAddress: { name: 'Rahul Sharma', phone: '9876543210', street: '45 MG Road', city: 'Gurugram', state: 'Haryana', pincode: '122001' },
    paymentMethod: 'COD',
    paymentStatus: 'pending',
    orderStatus: 'shipped',
    itemsPrice: 1998,
    shippingPrice: 0,
    totalPrice: 1998,
    trackingNumber: 'BLREV2025009876',
    createdAt: '2025-04-12T14:20:00Z',
  },
  {
    _id: 'ord3',
    user: { _id: 'user1', name: 'Rahul Sharma', email: 'rahul@example.com' },
    items: [
      { product: 'p5', name: 'Omega-3 Fish Oil 1000mg', image: MOCK_PRODUCTS[4].images[0], price: 699, quantity: 1, flavor: '', weight: '120 softgels' },
      { product: 'p10', name: 'Vitamin D3 + K2 (5000 IU)', image: MOCK_PRODUCTS[9].images[0], price: 499, quantity: 1, flavor: '', weight: '60 capsules' },
    ],
    shippingAddress: { name: 'Rahul Sharma', phone: '9876543210', street: '45 MG Road', city: 'Gurugram', state: 'Haryana', pincode: '122001' },
    paymentMethod: 'Card',
    paymentStatus: 'paid',
    orderStatus: 'processing',
    itemsPrice: 1198,
    shippingPrice: 0,
    totalPrice: 1198,
    trackingNumber: null,
    createdAt: '2025-04-17T09:45:00Z',
  },
];

export const MOCK_USER = {
  _id: 'user1',
  name: 'Demo User',
  email: 'demo@suppx.com',
  phone: '9999999999',
  isAdmin: true,
  token: 'mock-jwt-token-suppx-demo',
  address: { street: '12 Fitness Street', city: 'Delhi', state: 'Delhi', pincode: '110001' },
};
